### PR TITLE
fix: Postgres lock to renew connection on EofException

### LINKED ISSUE #1784: TGs locks cannot recover from a connection being closed
It happened recently that YAT was doing a restart of Postges on renkulab. While all the services (read EL) recovered well, TGs, specifically the locks, couldn't recover from the connections being closed and kept raising this exception:
```
WARN  application - Acquiring postgres advisory lock failed! Retry in 500 milliseconds.
 		at flatten$extension @ skunk.util.Pool$.$anonfun$ofF$2(Pool.scala:120)
 		at delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.withReadBuffer(SocketPlatform.scala:52)
 		at flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$read$1(SocketPlatform.scala:82)
 		at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:114)
 		at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:120)
 		at as @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$8(SocketGroupPlatform.scala:76)
 		at skunk.net.BitVectorSocket$$anon$1.$anonfun$readUntilN$1(BitVectorSocket.scala:53)
 	skunk.exception.EofException: EOF was reached on the network socket.

 	🔥
 	🔥       Hint: Discard this session and retry with a new one.
 	🔥             the connection had closed.
 	🔥     Detail: Attempt to read 5 byte(s) failed after 0 bytes(s) were read, because
 	🔥    Problem: EOF was reached on the network socket.
 	🔥
 	🔥  EofException
 	🔥
 	skunk.exception.EofException:
 	2023-11-10 15:52:33,404 ERROR application - Failed to write lock stats record for key=-2110443704
 		at flatten$extension @ skunk.util.Pool$.$anonfun$ofF$2(Pool.scala:120)
 		at delay @ fs2.io.net.SocketCompanionPlatform$BufferedReads.withReadBuffer(SocketPlatform.scala:52)
 		at flatMap @ fs2.io.net.SocketCompanionPlatform$BufferedReads.$anonfun$read$1(SocketPlatform.scala:82)
 		at async @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.readChunk(SocketPlatform.scala:114)
 		at delay @ fs2.io.net.SocketCompanionPlatform$AsyncSocket.$anonfun$readChunk$1(SocketPlatform.scala:120)
 		at as @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$8(SocketGroupPlatform.scala:76)
 		at skunk.net.BitVectorSocket$$anon$1.$anonfun$readUntilN$1(BitVectorSocket.scala:53)
 	skunk.exception.EofException: EOF was reached on the network socket.

 	🔥
 	🔥       Hint: Discard this session and retry with a new one.
 	🔥             the connection had closed.
 	🔥     Detail: Attempt to read 5 byte(s) failed after 0 bytes(s) were read, because
 	🔥    Problem: EOF was reached on the network socket.
 	🔥
 	🔥  EofException
 	🔥
 	skunk.exception.EofException:
```

Only restarting TGs helped.

### PR DESCRIPTION
**Pull request by jachro**
closes #1784

### CODE REVIEW

**Review by eikek — APPROVED** [review]

File: graph-commons/src/main/scala/io/renku/lock/PostgresLock.scala [hunk 1]
```diff
@@ -42,11 +43,18 @@ object PostgresLock {
...
+  def exclusive[F[_]: ApplicativeThrow: Temporal: Logger, A: LongKey](
       session:  Resource[F, Session[F]],
       interval: FiniteDuration = 0.5.seconds
   ): Lock[F, A] =
-    Kleisli(key => session.flatMap(exclusive_[F, A](_, interval).run(key)))
+    Kleisli { key =>
+      def createLock: Resource[F, Unit] =
+        session
+          .flatMap(exclusive_[F, A](_, interval).run(key))
+          .handleErrorWith[Unit, Throwable](_ => Resource.eval(Temporal[F].sleep(interval * 2)) >> createLock)
```
Comment (eikek) [inline graph-commons/src/main/scala/io/renku/lock/PostgresLock.scala:54]: Not sure about this one: wouldn't we here catch again all exceptions and retry?
