### PR TITLE
fix: user's projects API to return all not activated projects

### LINKED ISSUE #1232: There's some weirdness going on when getting the user's projects
It looks like there's something weird going on when calling the User Projects endpoint in the case when the user has more than the requested `per_page` number of projects in GL that are not activated in KG.

We simply do not load all pages from GL.

### PR DESCRIPTION
**Pull request by jachro**
closes #1232

### CODE REVIEW

File: knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/GLProjectFinder.scala [hunk 1]
```diff
@@ -60,14 +63,20 @@ private class GLProjectFinderImpl[F[_]: Async: GitLabClient: Logger](creatorFind
...
-      mapResponse
-    )(criteria.maybeUser.map(_.accessToken))
+  private def findProjectsAndCreators(criteria: Criteria, page: Page = Page.first): F[List[ProjectAndCreator]] =
+    GitLabClient[F]
+      .get(uri"users" / criteria.userId / "projects" withQueryParam ("page", page), "user-projects")(mapResponse)(
+        criteria.maybeUser.map(_.accessToken)
+      )
+      .flatMap {
+        case (results, None)           => results.pure[F]
+        case (results, Some(nextPage)) => findProjectsAndCreators(criteria, nextPage).map(results ::: _)
```
Comment (eikek) [inline knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/GLProjectFinder.scala:73]: We could also use a `fs2.Stream` to load it lazily (if we don't always need everything immediately). Might also help if GL should have some rate-limiting in place? Or should we handle this (better) explicitely?

File: knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/ProjectsFinder.scala [hunk 2]
```diff
@@ -51,7 +51,7 @@ private class ProjectsFinderImpl[F[_]: MonadThrow](
     (findProjectsInTS(criteria) -> findProjectsInGL(criteria))
       .mapN(mergeFavouringActivated)
       .map(filterBy(criteria.filters.state))
-      .map(_.sortBy(_.name))
+      .map(_.sortBy(_.name.value.toLowerCase))
```
Comment (eikek) [inline knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/ProjectsFinder.scala]: We could also define the `Ordering` for this `name` type? (since we have specific types)

**Review by eikek — APPROVED** [review]

File: knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/GLProjectFinder.scala (hunk 1 above)
Comment (jachro) [reply knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/GLProjectFinder.scala:73]: Yes, we could use streams here but actually, we need to fetch all the user projects as we then combine them with kg projects and only after we sort and page them on the Scala side. So I thought maybe it was not worth switching to Stream here.

File: knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/ProjectsFinder.scala (hunk 2 above)
Comment (jachro) [reply knowledge-graph/src/main/scala/io/renku/knowledgegraph/users/projects/finder/ProjectsFinder.scala]: Yes, good idea.
