### PR TITLE
fix: DS graph provisioning when many DS on one project with same sameAs

### LINKED ISSUE #1479: Issue on provisioning Datasets graph
Sentry Issue: [RENKU-GRAPH-E3](https://sentry.dev.renku.ch/organizations/sentry/issues/2306/?referrer=github_integration)

```
UnsupportedOperationException: empty.maxBy
    at scala.collection.IterableOnceOps.maxBy(IterableOnce.scala:1011)
    at scala.collection.IterableOnceOps.maxBy$(IterableOnce.scala:1009)
    at scala.collection.AbstractIterable.maxBy(Iterable.scala:933)
    at io.renku.entities.searchgraphs.commands.CommandsCalculatorImpl.io$renku$entities$searchgraphs$commands$CommandsCalculatorImpl$$findMax(CommandsCalculator.scala:167)
    at io.renku.entities.searchgraphs.commands.CommandsCalculatorImpl$DS$u0020exists$u0020on$u0020TS$u0020only$u0020along$u0020other$u0020projects$u0020$minus$u0020no$u0020info$u0020visibility$u0020change$.unapply(CommandsCalculator.scala:139)
...
(11 additional frame(s) were not displayed)

TriplesUploadResult$NonRecoverableFailure$NonRecoverableFailureWithCause: Transformation of omnibenchmark/iris_example/iris-parameters failed: java.lang.UnsupportedOperationException: empty.maxBy
    at io.renku.triplesgenerator.events.consumers.tsprovisioning.triplesuploading.TriplesUploadResult$NonRecoverableFailure$.apply(TransformationStepsRunner.scala:131)
    at io.renku.triplesgenerator.events.consumers.tsprovisioning.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunner.scala:95)
    at io.renku.triplesgenerator.events.consumers.tsprovisioning.triplesuploading.TransformationStepsRunnerImpl$$anonfun$transformationFailure$1.applyOrElse(TransformationStepsRunner.scala:93)
    at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:172)
    at cats.effect.IOFiber.failed(IOFiber.scala:1242)
...
(4 additional frame(s) were not displayed)

ADD_MIN_PROJECT_INFO: projectId = 22110, projectPath = omnibenchmark/iris_example/iris-parameters Transformation of omnibenchmark/iris_example/iris-parameters failed: java.lang.UnsupportedOperationException: empty.maxBy
```

### PR DESCRIPTION
**Pull request by jachro**
Apparently, the Dataset graph provisioning flow could not cope with a case when there were multiple Datasets on a single project having the same topmostSameAs and they all get removed.

closes #1479

### CODE REVIEW

File: entities-search/src/main/scala/io/renku/entities/searchgraphs/datasets/commands/SearchInfoFetcher.scala [hunk 1]
```diff
@@ -59,55 +59,55 @@ private class SearchInfoFetcherImpl[F[_]: Async: Logger: SparqlQueryTimeRecorder
...
-        |    }
-        |  }
-        |}
-        |GROUP BY ?topSameAs ?name ?visibility ?maybeDescription
-        |         ?maybeDateCreated ?maybeDatePublished ?maybeDateModified
-        |ORDER BY ?name
-        |""".stripMargin
+    sparql"""|SELECT DISTINCT ?topSameAs ?name ?visibility ?maybeDescription
+             |                ?maybeDateCreated ?maybeDatePublished ?maybeDateModified
+             |                (GROUP_CONCAT(?creator; separator=${rowsSeparator.asTripleObject}) AS ?creators)
```
Comment (eikek) [inline entities-search/src/main/scala/io/renku/entities/searchgraphs/datasets/commands/SearchInfoFetcher.scala:64]: Don't we have a conversion for `Char`? I think I've seen something like it somewhere, but not sure :-)

**Review by eikek — APPROVED** [review]

File: entities-search/src/main/scala/io/renku/entities/searchgraphs/datasets/commands/SearchInfoFetcher.scala (hunk 1 above)
Comment (jachro) [reply entities-search/src/main/scala/io/renku/entities/searchgraphs/datasets/commands/SearchInfoFetcher.scala:64]: Yes, I think I added that in one of my last PRs. Let me check...

Comment (jachro) [reply entities-search/src/main/scala/io/renku/entities/searchgraphs/datasets/commands/SearchInfoFetcher.scala:64]: Yes, we do have one :)
