### PR TITLE
fix: reduce number of threads required to track subscribers availability

### LINKED ISSUE #444: Event-log gets restarted
It looks there's some memory leakage which causes EL to restart.

Notice that the memory usage is gradually going up:
Screen Shot 2020-10-07 at 11 15 17

Hypothesis: Subscribers are getting freed up but there are too many of the objects which are freeing them. Each request has a thread. We fixed the thread pool. Cats IO creates fibers, which are a lightweight version of a thread. Looking at number of threads, all will always be used.

Instead we could just store the time when a subscriber should be freed up. Create a process which goes through subscribers to check for free ones.

### PR DESCRIPTION
**Pull request by travissarles**
closes #444

### CODE REVIEW

File: event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersRegistrySpec.scala [hunk 1]
```diff
@@ -0,0 +1,249 @@
...
+      subscribersRegistry.findAvailableSubscriber()          shouldBe Some(subscriberUrl)
+
+      val subscribersFound = (1 to 10).foldLeft(Set.empty[SubscriberUrl]) { (returnedSubscribers, _) =>
+        subscribersRegistry.findAvailableSubscriber().map(returnedSubscribers + _).getOrElse(returnedSubscribers)
+      }
+      subscribersFound shouldBe Set(subscriberUrl)
+    }
+  }
+
+  "start" should {
```
Comment (travissarles) [inline event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersRegistrySpec.scala:195]: Looks good

**Review by jachro — APPROVED** [review]
👍
