### PR TITLE
fix: delay execution of recoverably failed events

### LINKED ISSUE #802: Recoverable errors log statements cause noise
It might be wise to stop logging recoverable errors like below as they cause noise and do not bring much value if at all.

Two things might be worth addressing here:
- [x] re-thing the concept of RecoverableErrors structure
- [x] for token related recoverable errors might be worth moving the event execution time into the future more than the standard 5 min.

If there is no access token, we don't need to print this. We'll see this in Grafana because we'll see the events are being reprocessed every few minutes.  
However, if there is a network issue, we'd like to see this in the logs. 

```
ch.datascience.triplesgenerator.events.categories.triplesgenerated.triplescuration.IOTriplesCurator$CurationRecoverableError: Access token not valid to fetch project members
    at ch.datascience.triplesgenerator.events.categories.triplesgenerated.triplescuration.IOTriplesCurator$CurationRecoverableError$.apply(TriplesTransformer.scala:74)
    at ch.datascience.triplesgenerator.events.categories.triplesgenerated.triplescuration.persondetails.IOGitLabProjectMembersFinder$$anonfun$mapResponse$lzycompute$1.applyOrElse(GitLabProjectMembersFinder.scala:111)
    at ch.datascience.triplesgenerator.events.categories.triplesgenerated.triplescuration.persondetails.IOGitLabProjectMembersFinder$$anonfun$mapResponse$lzycompute$1.applyOrElse(GitLabProjectMembersFinder.scala:101)
    at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241)
    at ch.datascience.http.client.RestClient.processResponse(RestClient.scala:144)
    at ch.datascience.http.client.RestClient.$anonfun$callRemote$1(RestClient.scala:138)
    at cats.effect.Resource.$anonfun$fold$1(Resource.scala:123)
    at cats.effect.internals.IOBracket$BracketStart.liftedTree1$1(IOBracket.scala:95)
    at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:95)
    at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
    at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
    at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
    at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
    at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
    at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
    at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:137)
    at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:126)
    at org.http4s.client.blaze.Http1Connection.parsePrelude(Http1Connection.scala:370)
    at org.http4s.client.blaze.Http1Connection.$anonfun$handleRead$1(Http1Connection.scala:266)
    at org.http4s.client.blaze.Http1Connection.$anonfun$handleRead$1$adapted(Http1Connection.scala:265)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:448)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.lang.Thread.run(Thread.java:832)```

### PR DESCRIPTION
**Pull request by travissarles**
fix: delay execution of recoverably failed events
closes #802

### CODE REVIEW

File: event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala [hunk 1]
```diff
@@ -176,15 +177,41 @@ private object EventHandler {
...
+                                         executionDelay
+                               ).asRight
                              case status: TransformationNonRecoverableFailure =>
-                               ToFailure(eventId, projectPath, message, TransformingTriples, status).asRight
+                               ToFailure(eventId,
+                                         projectPath,
+                                         message,
+                                         TransformingTriples,
+                                         status,
+                                         executionDelay
```
Comment (travissarles) [inline event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala:213]: executionDelay = None

File: event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala [hunk 2]
```diff
@@ -176,15 +177,41 @@ private object EventHandler {
...
                              case status: GenerationRecoverableFailure =>
-                               ToFailure(eventId, projectPath, message, GeneratingTriples, status).asRight
+                               ToFailure(eventId,
+                                         projectPath,
+                                         message,
+                                         GeneratingTriples,
+                                         status,
+                                         executionDelay
+                               ).asRight
                              case status: GenerationNonRecoverableFailure =>
```
Comment (travissarles) [inline event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala:191]: same as below

File: triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessorSpec.scala [hunk 3]
```diff
@@ -116,7 +117,7 @@ class CommitEventProcessorSpec
         .expects(commitEvent, maybeAccessToken)
         .returning(leftT[Try, JsonLD](exception))
 
-      expectEventMarkedAsRecoverableFailure(commitEvent, exception)
+      expectEventMarkedAsRecoverableFailure(commitEvent, exception, ExecutionDelay(Duration.ofMinutes(5)))
```
Comment (travissarles) [inline triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessorSpec.scala:120]: modify case with table to include AuthRecoverableError
